#' Dissimilarity profile analysis (DISPROF & SIMPROF)
#'
#' This function follows Clarke et al.'s (2008) description of similarity profile
#' analysis (SIMPROF), but employs an equivalent approach based on dissimilarity
#' profile analysis (DISPROF).\cr
#' \cr
#' A null hypothesis of no multivariate structure is generated by calculating a
#' mean dissimilarity profile based on random permutations of the raw response
#' data. This approach follows a "Model 1: Environmental control over individual
#' species" permutational model described in Legendre & Legendre (2012:
#' page 619), whereby each column of data (i.e., the species) are permuted
#' separately.\cr
#' \cr
#' Note: when permuting the data, an internal check replaces NaN's with 1's;
#' this accounts for instances when permutation of the raw response data results
#' in more than one row consisting of all zeros, which in turn causes metrics
#' like the Bray-Curtis coefficient to returns NaN's after dividing 0 by 0.
#'
#' @references Clarke, K. R., P. J. Somerfield, and R. N. Gorley. 2008.  Testing
#'   null hypotheses in exploratory community analyses: similarity profiles and
#'   biota-environmental linkage. J. Exp. Mar. Biol. Ecol. 366:56-69.
#'   (\href{https://doi.org/10.1016/j.jembe.2008.07.009}{Clarke et al., 2008})
#' @references Legendre, P. & L. Legendre. 2012. Numerical ecology. 3rd English
#'   ed. Elsevier Science BV, Amsterdam. [p. 619]
#'
#' @param Y    Matrix of response data (rows = observations, columns = variables)
#' @param dis  Dissimilarity measure to be applied (see \code{vegan::vegdist}
#'   for additional details):
#' \itemize{
#'  \item Euclidean           (\code{'euc'})
#'  \item Bray Curtis         (\code{'bray'})
#'  \item Manhattan           (\code{'manhattan'})
#'  \item Gower's             (\code{'gower'})
#'  \item Alternative Gower's (\code{'altGower'})
#'  \item Canberra            (\code{'canberra'})
#'  \item Clark               (\code{'clark'})
#'  \item Kulczynski          (\code{'kulczynski'})
#'  \item Morisita            (\code{'morisita'})
#'  \item Horn                (\code{'horn'})
#'  \item Binomial            (\code{'binomial'})
#'  \item Cao                 (\code{'cao'})
#' }
#' @param iter Number of permutation for DISPROF analysis
#' @param verb Display results in the console window
#' @param plt Optionally create a DISPROF plot
#' @param verb2 internal flag for f_mstCluster
#'
#' @return Returns a list structure that contains the following:
#' \itemize{
#'  \item \code{D}: observed dissimilarity profile
#'  \item \code{meanD}: mean permuted dissimilarity profife
#'  \item \code{Pi}: Pi statistic (= deviation of observed vs. permuted mean profile)
#'  \item \code{p}: randomized probability
#' }
#'
#' @import ggplot2
#' @import stats
#'
#' @export

f_disprof <- function(Y,
                      dis   = 'euc',
                      iter  = 1000,
                      verb  = TRUE,
                      plt   = FALSE,
                      verb2 = TRUE){

### Set no. of iterations for permuted dissimilarity profile
if (iter < 1000) {
  iterM <- 1000 # need at least 1000
} else {
  iterM <- iter
}

### Ensure Y is in appropriate format for distance measures
Y <- as.matrix(Y)

### Create observed dissimilarity profile by calculating dissimilarities,
### unwrap, and sort in ascending order.
Y_dis <- vegan::vegdist(Y, dis, na.rm = TRUE)

D <- sort(as.vector(Y_dis))

### Calculate mean permuted dissimilarity profile
if (verb2 == TRUE) {
  cat("Calculating mean dissimilarity profile from", iterM-1, "permutations...")
}

permD <- matrix(0, length(D), iterM-1) # Preallocate

for (i in 1:(iterM-1)) {
  temp_D <- suppressWarnings(vegan::vegdist(apply(Y, 2, sample),
                                     dis,
                                     na.rm = TRUE))

  # Checks for and corrects NaN values in distance matrix resulting from
  # comparison of EMPTY ROWS (i.e., all zeros) after permutation
  temp_idx         <- which(is.nan(temp_D))
  temp_D[temp_idx] <- 1

  permD[,i]        <- sort(as.vector(temp_D))
}

rm(temp_D, temp_idx)

meanD <- apply(permD, 1, mean) # mean permuted dissimilarity profile

### Calculate deviation of observed profile vs. mean permuted profile
Pi <- sum(abs(D - meanD))

### Permutation tests:
if (iter > 0) {
  if (verb2 == TRUE) {
    cat("\nCalculating significance levels from", iter-1, "permutations...")
  }
  randPi <- rep(0, iter-1) # Preallocate

  # Create new permuted profile to compare to mean permuted profile
  for (i in 1:iter-1) { # observed value is considered a permutation
    temp_D <- suppressWarnings(vegan::vegdist(apply(Y, 2, sample),
                                       dis,
                                       na.rm = TRUE))

    # Checks for and corrects NaN values in distance matrix resulting from
    # comparison of EMPTY ROWS (i.e., all zeros) after permutation
    temp_idx         <- which(is.nan(temp_D))
    temp_D[temp_idx] <- 1

    randD            <- sort(as.vector(temp_D))

    randPi[i]        <- sum(abs(randD - meanD)) # permuted Pi test
  }
  p <- (sum(randPi >= Pi)+1) / (iter) # count values & convert to probability
} else {
  p <- NaN
}

if (verb == TRUE){
  cat("\n=======================================================",
      "\n        DISPROF - Dissimilarity Profile Analysis:      ",
      "\n-------------------------------------------------------",
      "\n Pi stat             = ", Pi,
      "\n p                   = ", p,
      "\n No. of permutations = ", iter,
      "\n-------------------------------------------------------")
}

### Optionally create a plot
if (plt == TRUE) {
  # get number of rows of D
  D_ord <- c(1:length(D))

  # Calculate 99% confidence envelopes
  plus_3SD  <- meanD + 3*apply(permD,1,sd)
  minus_3SD <- meanD - 3*apply(permD,1,sd)

  # Truncate so there are no negative similarities
  plus_3SD[plus_3SD < 0]   <- 0
  minus_3SD[minus_3SD < 0] <- 0

  DisProf_plt <- ggplot()+
    theme_classic()+
    theme(legend.position = c(0.90, 0.15))+
    labs(title    = "DISPROF: Dissimilarity Profile Analysis",
         subtitle = "(99% confidence envelope)",
         x        = "Sort Order",
         y        = "Dissimilarity")+
    geom_line(aes(x     = D_ord,
                  y     = D,
                  color = "Observed profile"),
              size  = 1.5)+
    geom_line(aes(x     = D_ord,
                  y     = meanD,
                  color = "Permuted mean"),
              size  = 1)+
    geom_ribbon(aes(x      = D_ord,
                    ymin   = minus_3SD,
                    ymax   = plus_3SD,
                    color  = "Permuted mean"),
                size        = 0.5,
                linetype    = "dashed",
                alpha       = 0.1,
                show.legend = FALSE)+
    scale_color_manual(name   = "",
                       values = c("Observed profile" = "blue",
                                  "Permuted mean"    = "black"))
  print(DisProf_plt)
}

### Return output
result       <- list() # Preallocate output structure

result$D     <- D      # Observed dissimilarity profile
result$meanD <- meanD  # mean permuted dissimilarity profile
result$Pi    <- Pi     # Pi statistic (= deviation of observed vs. permuted mean profile)
result$p     <- p      # randomized probability

return (result)
}
